#Print OS
fastfetch

#Aliases
alias clear='clear && fastfetch'

#Git-Credential-Manager
export GPG_TTY=$(tty)

#better color for autosuggestion
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#10C5AA,bold,underline"
